apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-crd
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
      universalAuth:
          secretsScope:
              projectSlug: nomai
              envSlug: "prod"
              secretsPath: "/ai-stickers"
          credentialsRef:
              secretName: universal-auth-credentials
              secretNamespace: default
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: ai-stickers
      creationPolicy: "Orphan"
      template:
          includeAllSecrets: true

